### ISSUE TITLE
How to retrive saved values in frontend from db 

### ISSUE THREAD

**Issue by varunsridharan** [keesiemeijer/WP-Settings#3]
How to retrive saved values in frontend from db 
i tried to use `$this->settings->get_settings()` but this works only in admin side.. how i can get it in front end

**Comment by keesiemeijer** [comment]
First add this to the admin page callback:

``` php
echo $this->settings->debug;
```

(See [the example](https://github.com/keesiemeijer/WP-Settings#example))

This will display the database option name(s) created when visiting the settings page. Get the option with `get_option()` using the name; 
https://codex.wordpress.org/Function_Reference/get_option
